services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: edulearn-app:latest
    container_name: edulearn-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"

    env_file:
      - .env.docker

    environment:
      APP_URL: ${APP_URL:-http://localhost:8000}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - storage_data:/var/www/storage

    networks:
      - edulearn-network

volumes:
  storage_data:
    driver: local

networks:
  edulearn-network:
    driver: bridge